/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocumentComponent: typeof import('./src/components/DocumentComponent.vue')['default']
    DocumentViewerComponent: typeof import('./src/components/DocumentViewerComponent.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    GraphComponent: typeof import('./src/components/GraphComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    ListDocumentComponent: typeof import('./src/components/ListDocumentComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDocumentComponent: typeof import('./src/components/SearchDocumentComponent.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
  }
}
