/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EssentialLink: typeof import('./src/components/HeaderLink.vue')['default']
    HeaderLink: typeof import('./src/components/HeaderLink.vue')['default']
    NetworkGraph: typeof import('./src/components/NetworkGraph.vue')['default']
    PaperCard: typeof import('./src/components/PaperCard.vue')['default']
    PaperList: typeof import('./src/components/PaperList.vue')['default']
    PaperViewer: typeof import('./src/components/PaperViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPaper: typeof import('./src/components/SearchPaper.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
